### ISSUE TITLE
Add support for multi-channel .ome.tiff

### ISSUE THREAD

**Issue by ArtemSokolov** [vanvalenlab/deepcell-applications#13]
Consider adding support for multi-channel .ome.tiff, by re-parameterizing
`--nuclear-image <file.tif> --membrane-image <file.tif>`
to
`--image <file.ome.tif> --nuclear-channel <int> --membrane-channel <int>`

As a possible feature, allow for multiple indices to be specified, renaming the parameters to `--nuclear-channels` and `--membrane-channels` accordingly.

Example code for reading .ome.tiff and other formats:
https://github.com/HMS-IDAC/UnMicst/blob/340a31de8873fa247ea502e778ef14acee56984e/UnMicst2.py#L754-L764

**Comment by willgraf** [comment]
This issue is fixed in the first [release 0.1.0](https://github.com/vanvalenlab/deepcell-applications/releases/tag/0.1.0).

`--nuclear-channel` and `--membrane-channel` default to 0 (expecting `--nuclear-image` and `--membrane-image` to be single channel), but both can accept multiple channels which get summed together into a single channel (e.g. "membrane" channel).

For images that contain both membrane and nuclear channels, just pass the same file path to both `--nuclear-image` and `--membrane-image` and set the corresponding channel(s).

Please re-open this issue if you don't think it's closed. And please make a new issue for anything you'd like to see added or improved!

**Comment by FloWuenne** [comment]
Hi @willgraf ,

I would like to re-open this issue and suggest the following change:

Change the default for --membrane-image to :
`"If not passed, and --membrane-channel is not -1, --nuclear-image is used instead.`

Instead of the current way of reading two separate files (one for nuclear and one for membrane), this would only read a large multi-channel image once and would be more in line with the idea of using large, multi-channel images.
