### ISSUE TITLE
Adding conda package for mesmer

### ISSUE THREAD

**Issue by FloWuenne** [vanvalenlab/deepcell-applications#37]
Hi Deepcell-applications team,

we have written a nf-core DSL2 nextflow module to run Mesmer as part of nextflow imaging pipelines (https://github.com/nf-core/modules/pull/3187). In an effort to support conda,docker and singularity, nf-core likes packages to be submitted to bioconda. This also will enable an automatic docker container creation using quay.io (via biocontainers). Is there any chance you could consider submitting mesmer to bioconda?

Cheers,

Florian

**Comment by rossbar** [comment]
> nf-core likes packages to be submitted to bioconda. This also will enable an automatic docker container creation using quay.io (via biocontainers). Is there any chance you could consider submitting mesmer to bioconda?

My personal sense is - go for it! Anyone interested in submitting a recipe to conda-forge is more than welcome to do so. I'm not sure it would make sense to do so for `deepcell-applications` specficially, since this is just a thin CLI wrapper around models implemented with `deepcell-tf`. I suspect the three packages that would need recipes are `deepcell-tf`, `deepcell-tracking` and `deepcell-toolbox`. The former two are (or should be) trivial as they are pure Python in the packaging sense. `deepcell-toolbox` does include binary extensions and therefore needs and actual build recipe.

**Comment by FloWuenne** [comment]
So I don't think we will do this because of missing bandwith. If anyone else wants to tackle this, feel free! I will close this issue due to the fact that my question was answered @rossbar !
