### ISSUE TITLE
Remove Entrypoint from Docker image

### ISSUE THREAD

**Issue by FloWuenne** [vanvalenlab/deepcell-applications#41]
Hi Deepcell / Mesmer team,

we are using deepcell-applications / mesmer frequently in our Nextflow pipelines and created an nf-core module for other people to easily have access to the CLI for performing segmentation on tissue images: https://nf-co.re/modules/deepcell_mesmer

We are having some problems with the container when running it in Nextflow, due to the Entrypoint, which requires specific settings in Nextflow to be able to run, that we would like to avoid. Furthermore, these issues trickle down now to Wave container generation.

We think a simple fix for this would be to simply remove the Entrypoint layer from the container and let users just specify `python run_app.py` when running the container. 

https://github.com/vanvalenlab/deepcell-applications/blob/8aae5b6422a2773a05a4b8cc7c58fdfb88dc97bf/Dockerfile#L18

Would this be something you would consider doing for a new version of the container?

**Comment by rossbar** [comment]
The entrypoint is how we specify the the API for users; removing change behavior for anyone else relying on the container - therefore removing it wouldn't be possible.

I'd recommend forking and creating/hosting a docker image based on this one that meets your needs.

**Comment by FloWuenne** [comment]
Thanks for the quick answer @rossbar . Totally understand that you can't change behaviour of the container due to existing applications using it. 

Unfortunately with the newest version of deepcell, it seems like one needs a token to build the container? Is a token also required to perform inference? If this is the case, how would one handle usage of Mesmer in open-source applications like Nextflow and nf-core?

If we can somehow get around or manage the TOKEN requirement, then we can of course fork and build the container without the entrypoint 👍🏻 !

**Comment by rossbar** [comment]
The token requirement was added in `deepcell-tf` 0.12.7 in order to better enforce the [licensing terms](https://github.com/vanvalenlab/deepcell-tf/blob/master/LICENSE) of the deepcell project - i.e. attribution-based redistributability for academic use only.

As of 0.12.7, all `deepcell-tf`-based code depends on this authentication system, so it's something that you'd have to account for in your workflows. Individual workflow users can apply for tokens at https://users.deepcell.org.

The only way "around" this is to pin to older versions of deepcell-tf. Note however that thought these versions don't implement the authentication system, they are still subject to the same licensing terms!
